repos:
- repo: https://github.com/grantjenks/blue
  rev: v0.9.1
  hooks:
    - id: blue
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
    - id: check-json
    - id: check-yaml
- repo: https://github.com/rubik/xenon
  rev: v0.9.0
  hooks:
  - id: xenon
    args: ['--max-absolute=B', '.']
